version: '3.9'
services:
  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "root"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - rede
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Fiap.Desafio.Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - ConnectionStrings__DatabaseConnection=Server=db;Database=db;Uid=root;Pwd=123456;
    networks:
      - rede
    command: >
      /bin/sh -c "
      dotnet tool install --global dotnet-ef &&
      export PATH=\"$PATH:/root/.dotnet/tools\" &&
      dotnet ef database update &&
      dotnet Fiap.Desafio.Api.dll
      "
networks:
  rede:
